travis:
  secure:
    BINSTAR_TOKEN: YoBAxt1dpztZxFxJoYQh0DfgWRakbaDOWht41Iinj5lrOqr+fwTanFs++wgV4IRO1daFXRP00i5mAFU0ramOGbYROaBJuq+HIh5UQ6/pJB3RylFunHs7kUHte+MICa7GqKabmWLTa0Fz/HaX+0/wAixnjbzvpYv//LSEfm3lm9NNbs6pxVdX4kEiN501E9jAniPcNbV+1PCwe2odamqAHsliaZo+h1CehGkyQg6WrVBre6vUl427/dyH56eMTGA7A26AH1pN4HQKW40ubOXOJxHjNXuVY6uce74mUkAPFZp8+2UMVyBnhaxeHLF6oOi230bxTgbgbHrbt8VDSORHafN1vJufOxF1FRqOUrvZ9YX3eQXywHxTssztKlgcao0l4OF4e09NwRBSOlRC12S0p0gexEQPIAbQ3AzUllOWSA5w4GiheE5PiAaZeT5Zqm3NWlZUAcJXtKERzDLe2Wej8CVWCJLc9piW/n5gdKAbKtcKXiZuWt0I81wIw/EshY2GFtLV86aiAp25vf1dwoyjHWms2zGKFMpqQy+pmmg1eIjFwu1wcJ6F925CVTVyX4Np1kvw+pp/9lDdkmMR01ZrJDf7vVZTDHiY+VjBXI6/8GcSfCPP2wuWbnErX3u7EQBi1MEBVYLYnX00vFluR5CJoRTOLJ2WH8s40tDdfltqLgw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
